---
-  hosts: all
   become: yes
   tasks:
    - name: i want to install wget
      apt: 
       name: wget
       state: present

    - name: i want to start webserver on ubuntu16 ansible nodes
      service:
       name: apache2
       state: started
       when: ansible_OS_family == "Debain"

    - name: i want to install tree on RedHat ansible nodes
      apt:
        name: tree
        state: present
      when: ansible_OS_family == "Debain"


   
       